# Generated by Django 5.0.8 on 2024-08-17 01:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Investments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(default='', max_length=80, verbose_name='Asset Name')),
                ('ticker', models.CharField(choices=[('AAPL', 'AAPL'), ('GOOGL', 'GOOGL'), ('MSFT', 'MSFT')], default='', max_length=50, unique=True, verbose_name='Ticker')),
                ('type_investment', models.CharField(choices=[('AÇÃO', 'AÇÃO'), ('FII', 'FII')], default='', max_length=4, verbose_name='Type Investment')),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Dividend Yield (DY)')),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Price')),
                ('value_patrimonial', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Value Patrimonial')),
                ('price_to_book_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='P/VP (Preço/Valor Patrimonial)')),
                ('maximum_price', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maximum Price')),
                ('recommendation', models.CharField(blank=True, choices=[('Comprar', 'Comprar'), ('Não Comprar', 'Não Comprar')], default='', max_length=20, verbose_name='Recommendation')),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/images/', verbose_name='Asset Image')),
                ('slug', models.SlugField(editable=False, max_length=200, verbose_name='Slug')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='LogoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_logo', models.ImageField(upload_to='layout/imagens', verbose_name='Image Logo')),
            ],
        ),
    ]
