# Generated by Django 5.0.8 on 2024-09-07 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Current Price'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Dividend Yield (DY)'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='maximum_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Maximum Price'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='recommendation',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Recommendation'),
        ),
        migrations.AlterField(
            model_name='investments',
            name='value_patrimonial',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, verbose_name='Value Patrimonial'),
        ),
    ]
