# Generated by Django 5.0.8 on 2024-09-07 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_investments_current_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investments',
            name='value_patrimonial',
        ),
    ]
