# Generated by Django 5.0.8 on 2024-09-08 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_investments_value_patrimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investments',
            name='dividend_yield',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Dividend Yield (DY)'),
        ),
    ]
